<?php
    //Turns on output offering
    //Output buffering allows you to have output of PHP (primarily generated by echo) stored into an memory (ie. buffer) instead of immediately transmitted to the browser or terminal. Which is useful to a variety of tasks:
    ob_start();
   //Using session to remember the value of input 
    session_start();

    $timezone = date_default_timezone_set("Asia/Kuala_Lumpur");

    $con = mysqli_connect("localhost","root","Shunzhivoon112893332030","swirlfeed");

    if(mysqli_connect_errno())
    {
        //mysqli_connect_errno() - returns the error code if the connection to the database failed
        echo "Connection has failed".mysqli_connect_errno();
    }
?>